{"facility": null, "severity": null, "timestamp": "2024-02-28T11:57:42.181478", "hostname": "windows_station", "app_name": "cribl", "process_id": "47425", "content": "Exception in thread \"main\" java.lang.NullPointerException"}
{"syslog_message": "    at com.example.App.method(App.java:42)"}
{"syslog_message": "    at com.example.App.main(App.java:20)"}
{"facility": null, "severity": null, "timestamp": "2024-02-28T11:57:42.181570", "hostname": "windows_station", "app_name": "rsyslog", "process_id": "23006", "content": "Traceback (most recent call last):"}
{"syslog_message": "    File \"script.py\", line 10, in <module>"}
{"syslog_message": "        value = my_list[10]"}
{"syslog_message": "IndexError: list index out of range"}